#####################################################################################################
#                                      Collectd configuration                                       #
#####################################################################################################
collectd:
  graphite_prefix: collectd.
  collectd_interval: 10
  ping_hosts:
    - host1.example.com
    - host2.example.com
  graphite_host: logging.example.com
