---
#
# Tasks for updating machines
#

- name: Update and Upgrade Debian/Ubuntu
  apt:
    upgrade: True
    update_cache: True
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Upgrade CentOS
  yum:
    name: '*'
    state: latest
    update_only: True
  when: ansible_distribution == "CentOS"

- name: Upgrade Fedora
  dnf:
    name: '*'
    state: latest
  when: ansible_distribution == "Fedora"

- name: Update and Upgrade Windows
  win_updates:
    category_names:
      - Application
      - Connectors
      - CriticalUpdates
      - DefinitionUpdates
      - DeveloperKits
      - FeaturePacks
      - Guidance
      - SecurityUpdates
      - ServicePacks
      - Tools
      - UpdateRollups
      - Updates
    reboot: True
  when: ansible_distribution == "Windows"
