---
#
# Tasks for configuring Kali Linux
#

- name: Update and Upgrade Debian/Ubuntu
  apt:
    upgrade: true
    update_cache: true
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Upgrade CentOS
  yum:
    name: '*'
    state: latest
    update_only: true
  when: ansible_distribution == "CentOS"

- name: Upgrade Fedora
  dnf:
    name: '*'
    state: latest
  when: ansible_distribution == "Fedora"

