---
#
# Playbook to install docker on an ubuntu 18.03 host
#


# Install Dotfiles for standard user
- hosts: docker-hosts
  gather_facts: True
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
    - ../group_vars/vault.yml
    - ../group_vars/vault.local.yml
    - ../group_vars/docker/docker.yml
    - ../group_vars/docker/docker.local.yml
  roles:
    - role: install_docker
      become: yes
      become_user: root
      become_method: sudo
