---
#
# Playbook to install Graphite, Carbon, Grafana, Dashboards and Collectd all on one machine
#

- hosts: monitorhost
  gather_facts: true
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - graphite
    - collectd-monitorhost
    - grafana
