version: '3.7'
services:
  service1:
    image: mlombanabaseimage:latest
    container_name: mlombanabaseimage
    hostname: baseimage
    restart: unless-stopped
    networks:
      internalnet: {}
      externalnet:
        ipv4_address: 1.2.3.4
    volumes:
      - /mnt/containers/baseimage:/mnt/containers/baseimage
    environment:
      - FOO=bar
    labels:
      - "server"
networks:
  internalnet:
    driver: bridge
    internal: true
  externalnet:
    external: true

