---

- name: Get the VM ID
  proxmox_kvm:
    agent: True
    timeout: 600
    api_user: "{{ proxmox.username }}"
    api_password: "{{ proxmox.password }}"
    api_host: "{{ proxmox.hostname }}"
    node: "{{ proxmox.node }}"
    name: "{{ inventory_hostname }}"
    state: current
  register: machine_status
  delegate_to: "{{ groups['proxmox_nodes'][0] }}"

- name: Create a snapshot
  command: "qm snapshot {{ machine_status.msg.split('=')[1].split(' ')[1] }} {{ snapshot_name }} --description 'Snapshot created by Ansible'"
  delegate_to: "{{ groups['proxmox_nodes'][0] }}"
