version: '3.7'
services:
  confluence:
    image: atlassian/confluence-server:latest
    container_name: confluence
    hostname: confluence
    restart: on-failure
    networks:
      - confluencenet
      - externalnet
    volumes:
      - /mnt/containers/confluence/confluence:/var/atlassian/application-data/confluence
    labels:
      - "server"

  postgresql:
    image: postgres:latest
    container_name: confluence_db
    hostname: confluence_db
    restart: on-failure
    networks:
      - confluencenet
    volumes:
      - /mnt/containers/confluence/postgres:/var/atlassian/application-data/confluence
    environment:
      - POSTGRES_USER=confluencedb
      # CHANGE THE PASSWORD!
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=confluencedb
      - POSTGRES_ENCODING=UTF8
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    labels:
      - "database"

networks:
  confluencenet:
    driver: bridge
    internal: true
  externalnet:
    external: true
