version: '3.7'
services:
  confluence:
    image: atlassian/confluence-server:latest
    container_name: confluence
    depends_on:
      confluence_db
    hostname: confluence
    restart: unless-stopped
    networks:
      confluencenet: {}
      vlan10net:
        ipv4_address: 10.10.10.128
    volumes:
      - /mnt/containers/confluence/confluence:/var/atlassian/application-data/confluence
    labels:
      - "server"

  confluence-postgresql:
    image: postgres:latest
    container_name: confluence_db
    hostname: confluence_db
    depends_on:
    restart: unless-stopped
    networks:
      - confluencenet
    volumes:
      - /mnt/containers/confluence/postgres:/var/atlassian/application-data/confluence
    environment:
      - POSTGRES_USER=confluencedb
      # CHANGE THE PASSWORD!
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=confluencedb
      - POSTGRES_ENCODING=UTF8
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    labels:
      - "database"

networks:
  confluencenet:
    driver: bridge
    internal: true
  vlan10net:
    external: true
