version: '3.7'
services:
  confluence:
    image: atlassian/confluence-server:latest
    container_name: confluence
    hostname: confluence
    volumes:
      - /mnt/containers/confluence/confluence:/var/atlassian/application-data/confluence
    ports:
      - '8090:8090'
      - '8091:8091'

  postgresql:
    image: postgres:latest
    container_name: confluence_db
    hostname: confluence_db
    volumes:
      - /mnt/containers/confluence/postgres:/var/atlassian/application-data/confluence
    environment:
      - POSTGRES_USER=confluencedb
      # CHANGE THE PASSWORD!
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=confluencedb
      - POSTGRES_ENCODING=UTF8
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
