version: '3.7'
services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    hostname: sabnzbd
    restart: unless-stopped
    networks:
      vlan11net:
        ipv4_address: 10.10.11.131
    volumes:
      - /mnt/containers/sabnzbd/config:/config
      - /mnt/media/New-Media/Completed:/downloads
      - /mnt/media/New-Media/In-Progress:/incomplete-downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      - "server"
networks:
  vlan11net:
    external: true
