# File used to configure settings

#####################################################################################################
#                                      Dotfiles configuration                                       #
#####################################################################################################
dotfiles_repo: http://github.com/example/dotfiles.git


#####################################################################################################
#                                           DNS configuration                                       #
#####################################################################################################
dns:
  dns_server: "1.2.3.4"
  forward_lookup_zone: "example.com"
  reverse_lookup_zone: "reverse.example.com"
  records:
    - name: record1
      ip: "10.20.30.40"


#####################################################################################################
#                                      Active Directory configuration                               #
#####################################################################################################
active_directory:
  domain: example.com
  realm: EXAMPLE
  domain_controller:
    name: dc
    ip: 10.20.30.40
  credentials:
    username: Administrator
    password: Password1!


#####################################################################################################
#                                      Collectd configuration                                       #
#####################################################################################################
collectd:
  graphite_prefix: collectd.
  collectd_interval: 10
  ping_hosts:
    - host1.example.com
    - host2.example.com
  graphite_host: logging.example.com


#####################################################################################################
#                                      Openstack configuration                                      #
#####################################################################################################
openstack:
  provision_list:
    - name: unixExample1
      image: "ubuntu-cloud-16.04"
      flavor: "c8.xlarge"
      key: "default-keypair"
      nics: "net-name=private-network"
      terminate_volume: true
      security_groups:
        - "default"
      floating_ip_pools:
        - "public-network"
      meta:
        default_user: ubuntu
        groups:
          - os_unix_hosts
    - name: windowsExample1
      image: "Windows Server 2012 R2"
      flavor: "c2.small"
      key: "default-keypair"
      nics: "net-name=private-network"
      terminate_volume: true
      security_groups:
        - "default"
      floating_ip_pools:
        - "public-network"
      meta:
        default_user: Administrator
        groups:
          - os_windows_hosts


#####################################################################################################
#                                         User configuration                                        #
#####################################################################################################
users:
  unix_users:
    - username: exampleUser1
      # password is Password1234!
      password: '$6$2QafErWNr1z$r1CPLPoqPjCceKxjdXQLDWS2zsOcwj8y8kAvyXihzmTSHrVEenvheFPTbmJzIbBLwLoJqYgBBZxZTFySXYg.d/'
      groups: []
    - username: exapleUser2
      # password is Password1234!
      password: '$6$2QafErWNr1z$r1CPLPoqPjCceKxjdXQLDWS2zsOcwj8y8kAvyXihzmTSHrVEenvheFPTbmJzIbBLwLoJqYgBBZxZTFySXYg.d/'
      groups:
        - sudo
  windows_users:
    - username: exampleUser3
      password: 'Password1234!'
      groups: []
    - username: exampleUser4
      password: 'Password1234!'
      groups:
        - "Power Users"
    - username: exampleUser5
      password: 'Password1234!'
      groups:
        - Administrators


#####################################################################################################
#                                      Proxmox configuration                                        #
#####################################################################################################
proxmox:
  username: root@pam
  password: toor
  hostname: proxmox.example.com
  provision_list:
    - name: examplevm
      node: node1
      image_source: Ubuntu-16.04-Template
      storage: local-lvm
      cores: 2
      sockets: 2
      memory: 4096
      meta:
        default_user: ubuntu
        groups:
          - proxmox_unix_hosts


#####################################################################################################
#                                        Kali configuration                                         #
#####################################################################################################
kali:
  user:
    username: user1
    # password is Password1234!
    password: '$6$2QafErWNr1z$r1CPLPoqPjCceKxjdXQLDWS2zsOcwj8y8kAvyXihzmTSHrVEenvheFPTbmJzIbBLwLoJqYgBBZxZTFySXYg.d/'
  ssh:
    port: 22
  packages:
    - kali-linux-all
    - veil
  tools:
    - name: Empire
      repo: https://github.com/EmpireProject/Empire.git
    - name: Deathstar
      repo: https://github.com/byt3bl33d3r/DeathStar.git
    - name: BloodHound
      repo: https://github.com/BloodHoundAD/BloodHound.git
    - name: Webshells
      repo: https://github.com/BlackArch/webshells.git
    - name: CrackMapExec
      repo: https://github.com/byt3bl33d3r/CrackMapExec.git
    - name: Merlin
      repo: https://github.com/Ne0nd0g/merlin.git
    - name: Powersploit
      repo: https://github.com/PowerShellMafia/PowerSploit.git
    - name: PayloadsAllTheThings
      repo: https://github.com/swisskyrepo/PayloadsAllTheThings.git
    - name: MalleableC2Profiles
      repo: https://github.com/rsmudge/Malleable-C2-Profiles.git
    - name: ImPacket
      repo: https://github.com/CoreSecurity/impacket.git


#####################################################################################################
#                                        Mount configuration                                        #
#####################################################################################################
mount:
  - share: "//fileserver.example.com/Files"
    directory: "/mnt/Files"
    options:
      uid: root
      gid: root
      other: 'ro' # optional, can be left out or empty
    fstype: cifs
    credentials: # optional, can be left out
      username: 'user1'
      password: 'pw1'
      pwfile: '/root/.examplepwfile'


#####################################################################################################
#                                     iptables configuration                                        #
#####################################################################################################
# Valid values
# Action: DROP, REJECT (DROP ignores packets, REJECT sends a CONN_REFUSED)
# protocol: tcp, udp
# port (incoming, destination, redirect, etc.): 0..65535
# source: network name, a hostname, a network IP address (with /mask), or a plain IP address
# destination: network name, a hostname, a network IP address (with /mask), or a plain IP address
iptables:
  allow_incoming_ports:
    # Allow new and established connections to tcp port 443
    - protocol: tcp
      port: 443
  deny_incoming_ports:
    # Drop all incoming packets to tcp port 22
    - protocol: tcp
      port: 22
      action: DROP
  redirect_incoming_ports:
    # Redirect all incoming packets to tcp port 80 to tcp port 443
    - protocol: tcp
      incoming_port: 80
      redirect_port: 443
  allow_incoming_hosts: # List the sources
    - 1.2.3.4 # allow all new and established connections from 1.2.3.4
  deny_incoming_hosts:
    # REJECT all incoming packets from 1.2.3.4
    - source: 1.2.3.4
      action: REJECT
  allow_specific_incoming_connection:
    # Allow all packets from 1.2.3.4 to udp port 53
    - protocol: udp
      source: 1.2.3.4
      port: 53
  deny_specific_incoming_connection:
    # DROP all packets from 1.2.3.4 to udp port 53
    - protocol: udp
      source: 1.2.3.4
      port: 53
      action: DROP

  allow_outgoing_ports:
    # Allow all outgoing connections to tcp port 80
    - protocol: tcp
      port: 80
  deny_outgoing_ports:
    # Deny all outgoing connections to udp port 53
    - protocol: udp
      port: 53
      action: DROP
  redirect_outgoing_ports:
    # Redirect all outgoing packets originally going to tcp port 80 to tcp port 443
    - protocol: tcp
      outgoing_port: 80
      redirect_port: 443
  allow_outgoing_hosts: # List the destinations
    - 1.2.3.4 # Allow all connections to host 1.2.3.4
  deny_outgoing_hosts:
    # Drop all connections going to 1.2.3.4
    - destination: 1.2.3.4
      action: DROP
  allow_specific_outgoing_connection:
    # Allow all connections going to tcp port 80 on 1.2.3.4
    - protocol: tcp
      destination: 1.2.3.4
      port: 80
  deny_specific_outgoing_connection:
    # Drop all connections going to tcp port 22 on 1.2.3.4
    - protocol: tcp
      destination: 1.2.3.4
      port: 22
      action: DROP
