# File used to configure settings
ssh_ password: toor
server-repos:
  - epel: http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
  - rpmfusion-free: http://download1.rpmfusion.org/free/el/updates/6/i386/rpmfusion-free-release-6-1.noarch.rpm
  - rpmfusion-nonfree: http://download1.rpmfusion.org/nonfree/el/updates/6/i386/rpmfusion-nonfree-release-6-1.noarch.rpm
workstation-repos:
  - negativo: http://negativo17.org/repos/fedora-negativo17.repo
  - rpmfusion-free: http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-24.noarch.rpm
  - rpmfusion-nonfree: http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-24.noarch.rpm
vim_plugins:
  - http://github.com/jistr/vim-nerdtree-tabs
  - http://github.com/majutshushi/tagbar
  - http://github.com/alvan/closetag
  - http://github.com/JamshedVesuna/vim-markdown-preview
  - http://github.com/tpope/vim-surround
  - http://github.com/nvie/vim-flake8
  - http://github.com/trusktr/seti.vim
  - http://github.com/Valloric/YouCompleteMe
  - http://github.com/davidhalter/jedi-vim
  - http://github.com/davidhalter/jedi
  - http://github.com/mbbill/undotree
  - http://github.com/scrooloose/nerdtree
  - http://github.com/csexton/trailertrash.vim
  - http://github.com/scrooloose/syntastic
  - http://github.com/severin-lemaignan/vim-minimap
  - http://github.com/airblade/vim-gitgutter
  - http://github.com/scrooloose/nerdcommenter


active_directory:
  domain: example.com
  realm: EXAMPLE
  domain_controller:
    name: dc
    ip: 10.20.30.40
  credentials:
    username: Administrator
    password: Password1!

become_pass: Password1!





# Openstack Machines to provision
provision_list:
  - name: unixExample1
    image: "ubuntu-cloud-16.04"
    flavor: "c8.xlarge"
    key: "default-keypair"
    nics: "net-name=private-network"
    terminate_volume: true
    security_groups:
      - "default"
    floating_ip_pools:
      - "public-network"
    meta:
      default_user: ubuntu
      groups:
        - os_unix_hosts
  - name: windowsExample1
    image: "Windows Server 2012 R2"
    flavor: "c2.small"
    key: "default-keypair"
    nics: "net-name=private-network"
    terminate_volume: true
    security_groups:
      - "default"
    floating_ip_pools:
      - "public-network"
    meta:
      default_user: Administrator
      groups:
        - os_windows_hosts




# Openstack lab machine users
users:
  unix_users:
    - username: exampleUser1
      # password is Password1234!
      password: '$6$2QafErWNr1z$r1CPLPoqPjCceKxjdXQLDWS2zsOcwj8y8kAvyXihzmTSHrVEenvheFPTbmJzIbBLwLoJqYgBBZxZTFySXYg.d/'
      groups: []
    - username: exapleUser2
      # password is Password1234!
      password: '$6$2QafErWNr1z$r1CPLPoqPjCceKxjdXQLDWS2zsOcwj8y8kAvyXihzmTSHrVEenvheFPTbmJzIbBLwLoJqYgBBZxZTFySXYg.d/'
      groups:
        - sudo

  windows_users:
    - username: exampleUser3
      password: 'Password1234!'
      groups: []
    - username: exampleUser4
      password: 'Password1234!'
      groups:
        - "Power Users"
    - username: exampleUser5
      password: 'Password1234!'
      groups:
        - Administrators
