# File used to configure settings

#####################################################################################################
#                                      Dotfiles configuration                                       #
#####################################################################################################
dotfiles_repo: http://github.com/example/dotfiles.git
