version: '3.3'
services:
  nginx:
    image: nginx:1.14
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "6443:6443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "loadbalancer"
