---

# Playbook to automate the setup and configuration of a linux-based os. This playbook assumes the os will operate in a server environment, and will install tools used for server administration

- hosts: servers
  gather_facts: false
  vars_files:
    - ../variables/all.yml
    - ../variables/all.local.yml
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_pass: "{{ ssh_password }}"
  roles:
    - copy-ssh-key

- hosts: servers
  gather_facts: true
  vars_files:
    - ./variables/all.yml
    - ./variables/all.local.yml
  roles:
    - hostname
    - repos
    - dotfiles
    - generate-ssh-key
    - git
    - { role: netdata, when: "{{ netdata }} == true"}
    - { role: collectd, when: "{{ collectd }} == true"}
    - crontab
    - update
    - reboot
