---

# Playbook to automate the setup and configuration of a linux-based os. This playbook assumes the os will operate in a desktop environment, and will install tools used for desktop administration


- hosts: workstations
  gather_facts: true
  vars_files:
    - ../variables/all.yml
    - ../variables/all.local.yml
  roles:
    - hostname
    - repos
    - dotfiles
    - generate-ssh-key
    - git
    - { role: netdata, when: "{{ netdata }} == true"}
    - { role: collectd, when: "{{ collectd }} == true"}
    - crontab
    - update
    - reboot
