---
#
#
#

- name: Unix Configuration
  import_tasks: unix.yml
  when: inventory_hostname in groups['os_unix_hosts']

- name: Windows Configuration
  import_tasks: windows.yml
  when: inventory_hostname in groups['os_windows_hosts']
