#####################################################################################################
#                                           DNS configuration                                       #
#####################################################################################################
dns:
  dns_server: "1.2.3.4"
  forward_lookup_zone: "example.com"
  reverse_lookup_zone: "reverse.example.com"
  records:
    - name: record1
      ip: "10.20.30.40"
