#####################################################################################################
#                                           DNS configuration                                       #
#####################################################################################################
dns:
  dns_server: "1.2.3.4"
  forward_lookup_zone: "example.com"
  reverse_lookup_zone: "reverse.example.com"
  records:
    A:
      - name: record1.example.com
        ip: "10.20.30.40"
    CNAME:
      - name: record2.example.com
        alias: record.example.com
