---
#
# Enroll a Unix machine in Active Directory
#

- name: Enroll Windows
  win_domain_membership:
    dns_domain_name: "{{ active_directory.domain }}"
    hostname: "{{ inventory_hostname }}"
    domain_admin_user: "{{ active_directory.credentials.username }}"
    domain_admin_password: "{{ active_directory.credentials.password }}"
    state: domain
    register: domain_state

- name: Reboot Machines
  win_reboot:
  when: domain_state.reboot_required

