---
# Clone the repo
- name: Clone Plex Repo
  git:
    repo: https://github.com/MattLombana/App-Plex.git
    dest: /opt/Plex

# docker-compose up
- name: Run docker-compose up
  community.general.docker_compose:
    project_src: /opt/Plex/Docker
    build: no
  register: plex_output

# - ansible.builtin.debug:
#     var: plex_output
