---
#
# Playbook to enroll a machine in active directory
#

- hosts: domain_members
  gather_facts: True
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
    - ../group_vars/vault.yml
    - ../group_vars/vault.local.yml
    - ../group_vars/ad.yml
  roles:
    - role: enroll_in_active_directory
      become: yes
      become_user: root
      become_method: sudo

