---
#
# Ansible playbook to setup and configure dotfiles
#

# Install Dotfiles for standard user
- hosts: unix_hosts
  gather_facts: True
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
    - ../group_vars/vault.yml
    - ../group_vars/vault.local.yml
  roles:
    - install_dotfiles

# Now do it for root
- hosts: unix_hosts
  gather_facts: True
  become: True
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
    - ../group_vars/vault.yml
    - ../group_vars/vault.local.yml
  roles:
    - install_dotfiles
