---
#
# Playbook to install an ELK Stack on an Ubuntu host
#

- hosts:
    - elkstack
  gather_facts: false
  vars_files:
    - ../group_vars/vault.yml
    - ../group_vars/vault.local.yml
  roles:
    - role: install_elastic_repo
      become: yes
      become_user: root
      become_method: sudo
    - role: install_elasticsearch
      become: yes
      become_user: root
      become_method: sudo
    - role: install_kibana
      become: yes
      become_user: root
      become_method: sudo
    - role: install_logstash
      become: yes
      become_user: root
      become_method: sudo
    - role: install_filebeats
      become: yes
      become_user: root
      become_method: sudo
